### ISSUE TITLE
Fails to start on DigitalOcean

### ISSUE THREAD

**Issue by fatlirmorina** [supertokens/supertokens-docker-mysql#4]
Hi,

I have recently created an app in DigitalOcean from your sources in containers

however there seems to be a problem which I am not aware as of yet, 

database gets initialized and server starts successfully but after some time the build fails

it could be due to PORT or server ip?

**Comment by rishabhpoddar** [comment]
I think a user on our discord had the same issue (maybe it was you?)

The solution was that Digital ocean checks for health on port 8080 by default. Changing it to 3567 should work.

Closing this issue for now, but feel free to reopen it.
